const express = require('express');
const adminController = require('./admin.controller');
const { protectAdmin } = require('./admin.middleware');
const router = express.Router();
router.use(protectAdmin);
router.get('/dashboard', adminController.getDashboard);
router.get('/users', adminController.getUsers);
router.get('/users/:id', adminController.getUser);
router.patch('/users/:id/moderate', adminController.moderateUser);
router.get('/verifications/pending', adminController.getPendingIdentities);
router.post('/users/:id/verify-identity', adminController.verifyIdentity);
router.get('/properties/review', adminController.getPropertiesForReview);
router.patch('/properties/:id/review', adminController.reviewProperty);
module.exports = router;
